//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17", IsNullable=false)]
public partial class Request {
    
    private RequestAttributes[] attributesField;
    
    private bool returnPolicyIdListField;
    
    private bool combinedDecisionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Attributes")]
    public RequestAttributes[] Attributes {
        get {
            return this.attributesField;
        }
        set {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ReturnPolicyIdList {
        get {
            return this.returnPolicyIdListField;
        }
        set {
            this.returnPolicyIdListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool CombinedDecision {
        get {
            return this.combinedDecisionField;
        }
        set {
            this.combinedDecisionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17")]
public partial class RequestAttributes {
    
    private RequestAttributesAttribute attributeField;
    
    private string categoryField;
    
    /// <remarks/>
    public RequestAttributesAttribute Attribute {
        get {
            return this.attributeField;
        }
        set {
            this.attributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17")]
public partial class RequestAttributesAttribute {
    
    private RequestAttributesAttributeAttributeValue attributeValueField;
    
    private string attributeIdField;
    
    private bool includeInResultField;
    
    /// <remarks/>
    public RequestAttributesAttributeAttributeValue AttributeValue {
        get {
            return this.attributeValueField;
        }
        set {
            this.attributeValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttributeId {
        get {
            return this.attributeIdField;
        }
        set {
            this.attributeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IncludeInResult {
        get {
            return this.includeInResultField;
        }
        set {
            this.includeInResultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17")]
public partial class RequestAttributesAttributeAttributeValue {
    
    private string dataTypeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
